testing = false
creds_path = "credentials/"

[slack]
bot_channel = "#rocket2"

[aws]
users_table = "users"
teams_table = "teams"
projects_table = "projects"
region = "us-west-2"

[github]
app_id = 26418
organization = "ubclaunchpad"

[auth]
signing_key_path = "credentials/signing_key"
